version: "3"
services:
  analysis:
    image: joelnitta/japan_ferns_review:3.6.0
    ports:
      - "8787:8787"
    volumes:
      - ".:/home/rstudio/japan_ferns_review"
    environment:
      DISABLE_AUTH: "true"
    working_dir: /home/rstudio/japan_ferns_review
