library(conflicted)
library(ape)
library(assertr)
library(assertthat)
library(broom)
library(drake)
library(fs)
library(here)
library(janitor)
library(jntools)
library(magrittr)
library(maps)
library(multcomp)
library(patchwork)
library(picante)
library(readxl)
library(scales)
library(scico)
library(tidyverse)

conflict_prefer("map", "purrr")
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("gather", "tidyr")
